<?php 
session_start(); //esta linea tiene que ir antes de cualquier cosa, incluso de espacios 
//ob_start(); 
require 'fpdf/fpdf.php';

$a= $_SESSION['ruc']; 
$b= $_SESSION['razon'];
$z= $_SESSION['comercial']; 
$c= $_SESSION['estado']; 
$d= $_SESSION['clase'];
$e= $_SESSION['inicio']; 
$f= $_SESSION['actualizacion'];
$g= $_SESSION['suspension']; 
$h= $_SESSION['reinicio'];
$i= $_SESSION['obligado']; 
$j= $_SESSION['tipo'];
$k= $_SESSION['numero']; 
$l= $_SESSION['nombre'];
$m= $_SESSION['calle']; 
$n= $_SESSION['numer'];
$ñ= $_SESSION['interseccion']; 
$o= $_SESSION['establecimiento'];
$p= $_SESSION['provincia']; 
$q= $_SESSION['canton'];
$s= $_SESSION['parroquia'];
$t= $_SESSION['codigo']; 
$w= $_SESSION['actividad'];

//$c= $_SESSION['estado'];
//echo $a;
//echo $b;
//echo $c;

$pdf = new FPDF();
$pdf->AddPage();
$pdf->SetFont('Arial','', 13);
$pdf->Write (7,'DETALLES');
$pdf->Ln();

$pdf->Cell(90,43,"Numero de ruc : ".$a);
$pdf->Ln(9);
$pdf->Cell(90,43,"Razon social : ".$b);
$pdf->Ln(9);
$pdf->Cell(90,43,"Nombre comercial : ".$z);
$pdf->Ln(9);
$pdf->Cell(90,43,"Estado contribuyente : ".$c);
$pdf->Ln(9);
$pdf->Cell(90,43,"Clase contribuyente : ".$d);
$pdf->Ln(9);
$pdf->Cell(90,43,"Fecha de inicio de actividades : ".$e);
$pdf->Ln(9);
$pdf->Cell(90,43,"Fecha de actualizacion : ".$f);
$pdf->Ln(9);
$pdf->Cell(90,43,"Fecha de suspencion definitiva : ".$g);
$pdf->Ln(9);
$pdf->Cell(90,43,"Fecha de reinicio de actividades : ".$h);
$pdf->Ln(9);
$pdf->Cell(90,43,"Obligado : ".$i);
$pdf->Ln(9);
$pdf->Cell(90,43,"Tipo de contribuyente : ".$j);
$pdf->Ln(9);
$pdf->Cell(90,43,"Numero de establecimiento : ".$k);
$pdf->Ln(9);
$pdf->Cell(90,43,"Nombre de fantasia comercial : ".$l);
$pdf->Ln(9);
$pdf->Cell(90,43,"Calle : ".$m);
$pdf->Ln(9);
$pdf->Cell(90,43,"Numero : ".$n);
$pdf->Ln(9);
$pdf->Cell(90,43,"Interseccion : ".$ñ);
$pdf->Ln(9);
$pdf->Cell(90,43,"Estado del establecimiento : ".$o);
$pdf->Ln(9);
$pdf->Cell(90,43,"Descripcion de la provincia : ".$p);
$pdf->Ln(9);
$pdf->Cell(90,43,"Descripcion del canton : ".$q);
$pdf->Ln(9);
$pdf->Cell(90,43,"Descripcion de la parroquia : ".$s);
$pdf->Ln(9);
$pdf->Cell(90,43,"Codigo CIIU : ".$t);
$pdf->Ln(9);
$pdf->Cell(90,43,"Actividad economica : ".$w);
$pdf->Output();